export { default as LandingPage } from "./Authorization/LandingPage/LandingPage.component";
export { default as Login } from "./Authorization/Login/Login.component";
export { default as Signup } from "./Authorization/Signup/Signup.component";
export { default as PasswordReset } from "./Authorization/PasswordReset/PasswordReset.component";
export { default as EmailSent } from "./Authorization/EmailSent/EmailSent.component";
export { default as ForgottenPassword } from "./Authorization/ForgottenPassword/ForgottenPassword.component";
export { default as HealthWellbeing } from "./HealthWellbeing/HealthWellbeing.component";
export { default as MyConditions } from "./subpages/MyHealthRecords/MyConditions/MyConditions.component";
export { default as MyConditionDetails } from "./subpages/MyHealthRecords/MyConditions/MyConditionDetails/MyConditionDetails.component";
export { default as MyProcedures } from "./subpages/MyHealthRecords/MyProcedures/MyProcedures.component";
export { default as MyTestResults } from "./subpages/MyHealthRecords/MyTestResults/MyTestResults.component";
export { default as MyDocumentation } from "./subpages/MyHealthRecords/MyDocumentation/MyDocumentation.component";
export { default as MyAllergies } from "./subpages/MyHealthRecords/MyAllergies/MyAllergies.component";
export { default as MyAllergyDetails } from "./subpages/MyHealthRecords/MyAllergies/MyAllergyDetails/MyAllergyDetails.component";
export { default as Dashboard } from "./Dashboard/Dashboard.component";

export { default as CareContactsDashboardCard } from "./Dashboard/CareContacts/CareContactsDashboardCard.component";
export { default as Caresphere } from "./subpages/Caresphere/Caresphere.component";
export { default as HealthTracker } from "./HealthTracker/HealthTracker.component";
export { default as MyDetails } from "./subpages/MyHealthRecords/MyDetails/MyDetails.component";
export { default as MyQuestionnaires } from "./subpages/Documents/MyQuestionnaires/MyQuestionnaires.component";
export { default as Documents } from "./subpages/Documents/Documents.component";
export { default as CurrentMedications } from "./subpages/CurrentMedications/CurrentMedications.component";
// export { default as Notifications } from "./Dashboard/Notifications/Notifications.component";
export { default as NotificationsPopUp } from "../components/PageHeader/Notifications/NotificationsPopUp/Notifications.component";
export { default as VisitHistoryDashboardCard } from "./Dashboard/VisitHistory/VisitHistoryDashboardCard.component";
export { default as MyVisits } from "./subpages/MyVisits/MyVisits.component";
export { default as MyVisitDetails } from "./subpages/MyVisits/MyVisitDetails/MyVisitDetails.component";
export { default as account } from "../../assets/img/icons/account.svg";
export { default as blueArrowIcon } from "../../assets/img/icons/blueArrowSVG.svg";
export { default as Calendar} from "./Calendar/Calendar.component.jsx";
