export const allergies = [
  {
    Allergen: "Dairy foods",
    Severity: "Moderate",
    Reaction: "Diarrhea and vomiting",
    Category: "Food",
    OnsetDateTime: "08 April 2019, 00:00:00",
    RecordedDateTime: "25 November 2000 00:00:00",
    RecordedBy: "Paul Timms",
    PractitionerID: "60000000256931",
    AllergyType: "Food intolerance",
    IntoleranceType: "Intolerance",
    InformationSource: "Father/Mother",
    VerificationStatus: "Confirmed",
  },
  {
    Allergen: "Peanuts",
    Severity: "Severe",
    Reaction: "Acute allergic reaction",
    Category: "Food",
    OnsetDateTime: "08 April 2019, 00:00:00",
    RecordedDateTime: "25 November 2000 00:00:00",
    RecordedBy: "Paul Timms",
    PractitionerID: "60000000256931",
    AllergyType: "Food intolerance",
    IntoleranceType: "Intolerance",
    InformationSource: "Father/Mother",
    VerificationStatus: "Confirmed",
  },
  {
    Allergen: "Penicillin",
    Severity: "Moderate",
    Reaction: "Diarrhea and vomiting",
    Category: "Food",
    OnsetDateTime: "08 April 2019, 00:00:00",
    RecordedDateTime: "25 November 2000 00:00:00",
    RecordedBy: "Paul Timms",
    PractitionerID: "60000000256931",
    AllergyType: "Food intolerance",
    IntoleranceType: "Intolerance",
    InformationSource: "Father/Mother",
    VerificationStatus: "Confirmed",
  },
];
